### ISSUE TITLE
谁才能代表真正的中医？谁才能代表真正的苏格兰人？

### ISSUE THREAD

**Issue by Dafrok** [TCMExposed/SiteSource#1]
笑看研究生中医粉是如何给自己的大学丢脸的案例：
[刚看到一个例子，211大学研究生说：感冒优先吃感冒灵，中暑优先喝藿香正气水](https://tcmexposed.github.io/2019/07/13/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9C%89%E4%BA%BA%E8%AE%A4%E4%B8%BA%E4%B8%AD%E5%8C%BB%E8%8D%AF%E6%9C%89%E6%95%88-747290077.html)

[中医师非蠢即坏拿自杀事件抹黑感冒药](https://tcmexposed.github.io/2019/05/15/%E5%A6%82%E4%BD%95%E8%AF%84%E4%BB%B7-%E5%9B%9E%E9%A1%BE%E4%B8%AD%E8%8D%AF%E6%B3%A8%E5%B0%84%E5%89%82%E7%A0%94%E5%8F%91%E7%9A%84%E5%8E%86%E5%8F%B2-%E4%B8%BA%E4%B8%AD%E8%8D%AF%E6%B3%A8%E5%B0%84%E5%89%82%E8%AF%B4%E4%B8%80%E4%BA%9B%E8%AF%9D-684384831.html)

[中医理论博士逻辑连小学生都不如](https://tcmexposed.github.io/2019/03/30/%E4%B8%AD%E5%8C%BB-%E4%B8%BA%E4%BD%95%E4%B8%8D%E5%BA%9F%E5%8C%BB%E9%AA%8C%E8%8D%AF-636641943.html)

[中医科研人员睁着眼睛说瞎话，明明不推荐使用的论文拿出来证明针灸疗效毫无疑问](https://tcmexposed.github.io/2018/11/19/%E8%AF%B7%E5%AD%A6%E5%8C%BB%E7%9A%84%E4%B8%93%E4%B8%9A%E4%BA%BA%E5%A3%AB%E6%9D%A5%E8%AF%B4%E4%B8%80%E8%AF%B4-%E5%88%B0%E5%BA%95%E4%B8%AD%E5%8C%BB%E6%9C%89%E6%B2%A1%E6%9C%89%E5%AD%98%E5%9C%A8%E7%9A%84%E4%BB%B7%E5%80%BC-534311558.html)

最后，ICD 说白了就是个词典收录了传统医学的名词：
https://www.zhihu.com/question/296305024/answer/499625632

https://www.zhihu.com/question/296402829/answer/502467363

据《自然》新闻9月26日报道，世卫组织最高权力机构——世界卫生大会将于2019年推出该组织的第11版全球医学纲要，首次将中医传统医学相关信息纳入传统医学分类体系的章节。全球医学纲要也被称为国际疾病与相关健康问题统计分类（ICD），决定了100多个国家的诊疗过程。新纳入的全球医学纲要将于2022年在世卫组织成员国实施。

> 参考：
> https://www.thepaper.cn/newsDetail_forward_2481470
> https://weibo.com/1642512402/GBqmEm9Bn

**Comment by ZhongCitizen** [comment]
报道说“将中医传统医学相关信息纳入传统医学分类体系”，你竟能读出“中医已经合流为现代医学”的意思？

看清了，是将中医纳入传统医学分类体系！

**Comment by Dafrok** [comment]
`中医传统医学`

**Comment by Dafrok** [comment]
首先，`中医传统医学` 和 `中医` 就是有区别的

**Comment by Dafrok** [comment]
首先，`中医传统医学` 和 `中医` 就是有区别的，具体参考以下内容（摘自 wiki ）

https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8C%BB%E5%AD%A6#%E7%8E%B0%E4%BB%A3%E4%B8%AD%E5%8C%BB%E5%8F%B2

中医学定义：
> 以中医药理论与实践经验为主体，研究人类生命活动中健康与疾病转化规律及其预防、诊断、治疗、康复和保健的综合性科学

现代中医史：
> 受到西方冲击后，大多认为中医是充满偏方与迷信的医学，但上个世纪50年代，中国又开始研究中西医结合，并且透过对疗程的原理的科学性分析，重新认识到了中医的精妙之处，被主流学界所再度认可，而这样系统化的整理、导入西方生物、分子医学等概念成就了现代中医，也从空虚的阴阳调和概念，变成打下了扎实的学理基础。

现代中医的革新发明：
> 相较于传统中医，现代中医的革新发明例如：小针刀，传统药物注射制剂，科学中药等。

现代中医基础理论：
> 现代中医学则可分基础医学及临床医学两大部分
> 基础中医学：包括中医基础理论、中医诊断学、中药学、方剂学、内经、伤寒论、温病学、中国中医学>史、中医各家学说等；
> 临床中医学：包括中医内科、中医外科、中医妇科、中医儿科、针灸科、中医骨伤科、推拿科、中医眼科、中医耳鼻咽喉科、中西医结合医学、气功科、中医护理等。

关于合流：
> 自从近现代医学（又称西洋医学）随着传教士由欧洲传入中国之后，两种医学体系的竞争与融合就一直在进行。

**Comment by ZhongCitizen** [comment]
又来真正的中医、真正的穆斯林这一套？想要争功论赏的时候，江湖郞中的砒霜治白血病就归功到中医头上了，想要甩锅的时候，中医科学院也被开除出“真正的中医”队伍了。中医粉就只有耍嘴皮子甩锅的本事。
随你怎么换名字，反正挂个现代中医的招牌还是照样被吊打。

这里就有个“中医科学院被开除真正中医”的案例，看看中医粉是怎么打滚的：

[中医带电推拿是什么原理？](https://tcmexposed.github.io/2017/09/23/%E4%B8%AD%E5%8C%BB%E5%B8%A6%E7%94%B5%E6%8E%A8%E6%8B%BF%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E7%90%86-234182352.html)

**Comment by ZhongCitizen** [comment]
你看收录的文章几乎篇篇都是在打所谓的“现代中医”的脸。好好看，好好学。


[中医的整体理论体系是否正确有效？](https://tcmexposed.github.io/2017/01/22/%E4%B8%AD%E5%8C%BB%E7%9A%84%E6%95%B4%E4%BD%93%E7%90%86%E8%AE%BA%E4%BD%93%E7%B3%BB%E6%98%AF%E5%90%A6%E6%AD%A3%E7%A1%AE%E6%9C%89%E6%95%88-142294186.html)


[你听信过最久的谣言或谎言是什么？“科学无法解释中医理论，所以不能对中医下定论。”](https://tcmexposed.github.io/2017/12/11/%E4%BD%A0%E5%90%AC%E4%BF%A1%E8%BF%87%E6%9C%80%E4%B9%85%E7%9A%84%E8%B0%A3%E8%A8%80%E6%88%96%E8%B0%8E%E8%A8%80%E6%98%AF%E4%BB%80%E4%B9%88-274397113.html)

**Comment by ZhongCitizen** [comment]
多睁眼看看世界！搞得好像真正的中医很纯洁很无辜的样子。
红毛药酒、曹清华胶囊难道不是中药？凭什么让江湖郞中替中医背锅？

![image](https://user-images.githubusercontent.com/39447940/48178790-7dad4480-e356-11e8-8fdd-dde3c5d5cb3c.png)


[为什么要黑中医？](https://tcmexposed.github.io/2014/07/12/%E4%B8%BA%E4%BB%80%E4%B9%88%E8%A6%81%E9%BB%91%E4%B8%AD%E5%8C%BB-27889895.html)

[为什么曹清华胶囊就不能打假](https://tcmexposed.github.io/2017/12/09/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9B%B9%E6%B8%85%E5%8D%8E%E8%83%B6%E5%9B%8A%E5%B0%B1%E4%B8%8D%E8%83%BD%E6%89%93%E5%81%87-273518234.html)

这个牛化中医教授难道是江湖郞中？
[如何评价北京中医药大学教授称喝牛奶会导致「人的牛化」？](https://tcmexposed.github.io/2018/02/25/%E5%A6%82%E4%BD%95%E8%AF%84%E4%BB%B7%E5%8C%97%E4%BA%AC%E4%B8%AD%E5%8C%BB%E8%8D%AF%E5%A4%A7%E5%AD%A6%E6%95%99%E6%8E%88%E7%A7%B0%E5%96%9D%E7%89%9B%E5%A5%B6%E4%BC%9A%E5%AF%BC%E8%87%B4-%E4%BA%BA%E7%9A%84%E7%89%9B%E5%8C%96-328210825.html)

这些文章收录得真好，留着专门拿来打脸这些天真Naive中医粉。

**Comment by ZhongCitizen** [comment]
可怜的人啊，多睁眼看看世界吧，你看收录的文章几乎篇篇都是在打所谓的“现代中医”的脸。
哪一篇有说江湖郎中？你这不是无理取闹吗？

**Comment by ZhongCitizen** [comment]
你反对传统中医现存的糟粕理论？你懂什么叫糟粕？

中医科学院告诉你，现在的中医在研究些什么鬼：
[中医带电推拿是什么原理？](https://tcmexposed.github.io/2017/09/23/%E4%B8%AD%E5%8C%BB%E5%B8%A6%E7%94%B5%E6%8E%A8%E6%8B%BF%E6%98%AF%E4%BB%80%E4%B9%88%E5%8E%9F%E7%90%86-234182352.html)

中医学子亲口告诉你，现在的中医在学些什么东西：
[为什么会存在反中医的人？](https://www.zhihu.com/question/264164426/answer/277947721)

[为什么网络上反中医人越来越多？](https://www.zhihu.com/question/265720138/answer/298169974)

[为什么要黑中医？](https://www.zhihu.com/question/24184789/answer/113937970)

继续装瞎吧！装睡的人是永远叫不醒的！

**Comment by Dafrok** [comment]
我很清楚自己相信的是什么反对的是什么，比起看见【中医】二字就好像失去理智一样的人来说。

**Comment by Dafrok** [comment]
我很清楚自己相信的是什么反对的是什么，比起看见【中医】二字就好像失去理智一样的人来说，我不算太可怜。

**Comment by ZhongCitizen** [comment]
什么”滥用中医一词指代江湖郎中欠妥“，这里收录的文章多是批判的中医理论和中医教授，哪里指代江湖郎中了？你简直是睁着眼睛说瞎话，故意转移话题李代桃僵。

表面一副理中客的样子，其实是睁着眼睛说瞎话，真不要脸。

**Comment by ZhongCitizen** [comment]
作者：马前卒
链接：https://www.zhihu.com/question/296402829/answer/502467363
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

只看新闻标题的话，对大多数中医支持者来说是振奋人心的大喜事。研究一下内容就未必了……我们还是从原新闻说起：澎湃新闻9月27日消息，中医在全球范围或将跻身成为主流疗法，而非仅仅作为手术、放疗等标准疗法之外的补充替代疗法。据《自然》新闻9月26日报道，世卫组织最高权力机构——世界卫生大会将于2019年推出该组织的第11版全球医学纲要，首次纳入中医传统医学的相关信息。全球医学纲要也被称为国际疾病与相关健康问题统计分类（ICD），在全球拥有绝对的影响力。中医将首次被世界卫生组织纳入全球医学纲要，或跻身主流疗法​www.thepaper.cn虽然中医界一向不太认世卫组织的文件，但潜意识里还是很期盼认同的。这次中医被列入医学纲要，从中医爱好者到中医营销号，都将此视作里程碑式事件，大张旗鼓地宣传。但这个“全球医学纲要”到底意味着什么呢？一 词典对于全球医学纲要的内容，有关报道已经做出说明——疾病与相关健康问题统计的分类标准（ICD）。或者更直白地说，这是一本疾病分类的统计词典。目前全球通用的医学纲要，是第10版（ICD-10）。作为统计疾病与死因的国际通用词汇手册，ICD-10已经有43种译本，被117个国家采用。类似的词典在世界卫生组织还有很多，比如功能、残疾和健康的国际分类（ICF），健康干预的国际分类（ICHI），以及基于ICD、ICF的若干派生分类等。具体而言，ICD涵盖死因、疾病、伤害、症状、就诊原因、影响健康状况的因素与疾病的外部原因等。通过使用ICD，医护人员、研究人员、卫生部门、保险机构与政府财政部门，都可以在同一个国际标准下统计各类疾病发病率、各类死因的死亡率，并针对数据进行分析与决策。可以说，ICD就是一个提供给各国卫生部门的统计表格标准格式。例如，在现行ICD-10代码体系中，用来表示寻求医疗保健的患者因何种活动导致伤病的Y93代码序列，是这个样子：
![image](https://user-images.githubusercontent.com/39447940/62028873-f2d9e600-b213-11e9-8151-066e94288ac1.png)
ICD-10代码体系中还有些令人脑洞大开的情况：W55与其它哺乳动物接触中的“被牛咬伤”、“被猪袭击”，V91船舶事故造成伤害中的“因滑水板着火导致的烧伤”等等。ICD已有一个半世纪的发展史。这个世界上每天都有千奇百怪的事故及伤亡，代码体系发展到今天包罗万象本身并不稀奇。ICD-11在新增第26章中，将中、日、韩的传统医学的病征描述用语纳入统计框架，反而来得过于晚了些。新增传统医学章节的确包含了经络、阴阳体质等中医概念内容，但仅仅是描述性记录归类，并非指导医疗。换言之，其性质相当于允许你将“骑车摔倒导致膝部受伤肿胀出血”之类的病征描述，写成“扑跌致经络气血郁滞，伤及血络”。虽然细则部分有待世卫组织公布，但总体来说只是拓展话术措辞而已。而且在ICD-11第26章的说明中，明确写到：对于那些想要记录有关传统医学实践的流行病学数据的人来说，使用ICD-11 TM章是可选的。本章不应用于死亡率报告。说白了，拓展序列可以给中医统计提供数据记录。至于死亡率，中医术语往往一个病征要对应若干现代医学病征，措辞含混缺乏量化与通用性，普及必然造成死因统计混乱。以流行病学为例，不同类型感染，如果都被记录为“时疫”，那简直是胡闹——当然，绝大部分人也不会把濒危家属往中医院送诊。作为一本疾病与死亡统计的专用词典，ICD-11却不认可传统医学的死亡统计效力，可见传统医学的地位。

**Comment by Dafrok** [comment]
我父亲是中国医科大学中医系毕业，且拥有执业药师资质，中西双修，虽然你删了我的评论我还是想重申，比起各路野鸡我更相信专家的话，更何况还是亲人。

**Comment by ZhongCitizen** [comment]
@Dafrok 来来来，西医专家来了！中医教授也来了！你爹比得过北京中医药大学教授吗？你爹有没有牛化？有脑子的用脑子，没脑子的自己没法分辨是非，光知道迷信专家。你自己对号入座吧。好好的脑子长在头上你不知道用，叹气。

[如何看待樊代明院士称洋鸡蛋是癌细胞 ？](https://www.zhihu.com/question/292367487/answer/480175295)


[如何评价北京中医药大学教授称喝牛奶会导致「人的牛化」？](https://tcmexposed.github.io/2018/02/27/%E5%A6%82%E4%BD%95%E8%AF%84%E4%BB%B7%E5%8C%97%E4%BA%AC%E4%B8%AD%E5%8C%BB%E8%8D%AF%E5%A4%A7%E5%AD%A6%E6%95%99%E6%8E%88%E7%A7%B0%E5%96%9D%E7%89%9B%E5%A5%B6%E4%BC%9A%E5%AF%BC%E8%87%B4-%E4%BA%BA%E7%9A%84%E7%89%9B%E5%8C%96-329399546.html)

[工程院副院长（内科专家）樊代明院士说西医方向错了，对吗？](https://tcmexposed.github.io/2018/08/26/%E5%B7%A5%E7%A8%8B%E9%99%A2%E5%89%AF%E9%99%A2%E9%95%BF-%E5%86%85%E7%A7%91%E4%B8%93%E5%AE%B6-%E6%A8%8A%E4%BB%A3%E6%98%8E%E9%99%A2%E5%A3%AB%E8%AF%B4%E8%A5%BF%E5%8C%BB%E6%96%B9%E5%90%91%E9%94%99%E4%BA%86-%E5%AF%B9%E5%90%97-478255472.html)


[如何看待樊代明院士称中医口服胎粪远远走在了西医肠菌移植的前面？](https://tcmexposed.github.io/2018/08/28/%E5%A6%82%E4%BD%95%E7%9C%8B%E5%BE%85%E6%A8%8A%E4%BB%A3%E6%98%8E%E9%99%A2%E5%A3%AB%E7%A7%B0%E4%B8%AD%E5%8C%BB%E5%8F%A3%E6%9C%8D%E8%83%8E%E7%B2%AA%E8%BF%9C%E8%BF%9C%E8%B5%B0%E5%9C%A8%E4%BA%86%E8%A5%BF%E5%8C%BB%E8%82%A0%E8%8F%8C%E7%A7%BB%E6%A4%8D%E7%9A%84%E5%89%8D%E9%9D%A2-480134323.html)

**Comment by ZhongCitizen** [comment]
说到亲人，那就更搞笑了，你爹比得过国医大师邓铁涛邓老吗？邓老一年半攻克艾滋病，果然牛化了。
[中医可以没逻辑到什么程度？](https://www.zhihu.com/question/333702762/answer/741252885)
有脑子不用，去信你的亲爹吧：
![image](https://user-images.githubusercontent.com/39447940/62097787-a2699380-b2ba-11e9-85ad-55684f33d90d.png)

https://www.zhihu.com/question/333702762/answer/741252885

**Comment by Dafrok** [comment]
: )

**Comment by Dafrok** [comment]
你看得懂『双修』两个字吗 : )

**Comment by ZhongCitizen** [comment]
@Dafrok  中医粉怎么都说话驴头不对马嘴的？你是想说你爹双修一下就不会像“西医院士樊代明+中医教授杨桢+国医大师邓铁涛”那样用傻逼言论捧中医了？反驳也反驳不到点上。按你的逻辑，国医大师邓铁涛误诊害死了自己的儿子，你爹中医水平不如国医大师邓铁涛，所以你爹不会害死你？所以你想证明中医水平越低的爹比较好？
